import type { TemplateData, RenderedWebsite } from '@/types/template';
import { loadTemplate } from './template-loader';
import { parseTemplate, parseCss, injectStyles, cleanupUnusedPlaceholders } from './template-parser';

/**
 * Template ve data'yı birleştirerek tam bir website render eder
 */
export async function renderWebsite(
  templateId: string,
  data: TemplateData,
  locale: string = 'en'
): Promise<RenderedWebsite> {
  try {
    // 1. Şablonu yükle
    const template = await loadTemplate(templateId, locale);
    
    // 2. CSS'i parse et (renkleri değiştir)
    const parsedCss = parseCss(template.css, data);
    
    // 3. HTML'i parse et (placeholder'ları değiştir)
    let parsedHtml = parseTemplate(template.html, data);
    
    // 4. CSS'i HTML'e enjekte et
    parsedHtml = injectStyles(parsedHtml, parsedCss);
    
    // 5. Kullanılmayan placeholder'ları temizle
    parsedHtml = cleanupUnusedPlaceholders(parsedHtml);
    
    // 6. Meta bilgileri ekle
    parsedHtml = injectMetaTags(parsedHtml, data);
    
    return {
      html: parsedHtml,
      css: parsedCss,
      templateId,
      locale,
      generatedAt: new Date().toISOString(),
    };
  } catch (error) {
    console.error('Error rendering website:', error);
    throw new Error(`Failed to render website: ${error}`);
  }
}

/**
 * Meta tag'leri ekle (SEO için)
 */
function injectMetaTags(html: string, data: TemplateData): string {
  const metaTags = `
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="${escapeAttribute(data.heroSubtitle)}">
    <meta name="keywords" content="${escapeAttribute(data.industry)}, ${escapeAttribute(data.businessName)}">
    <meta name="author" content="${escapeAttribute(data.businessName)}">
    <title>${escapeAttribute(data.businessName)} - ${escapeAttribute(data.heroTitle)}</title>
    
    <!-- Open Graph -->
    <meta property="og:title" content="${escapeAttribute(data.businessName)}">
    <meta property="og:description" content="${escapeAttribute(data.heroSubtitle)}">
    <meta property="og:type" content="website">
    
    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${escapeAttribute(data.businessName)}">
    <meta name="twitter:description" content="${escapeAttribute(data.heroSubtitle)}">
  `;
  
  // <head> içine ekle veya mevcut meta'ları güncelle
  if (html.includes('<head>')) {
    return html.replace('<head>', `<head>\n${metaTags}`);
  }
  
  return html;
}

/**
 * Attribute için escape
 */
function escapeAttribute(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Rendered HTML'i optimize et
 */
export function optimizeHtml(html: string): string {
  let optimized = html;
  
  // Fazla boşlukları temizle
  optimized = optimized.replace(/\s+/g, ' ');
  
  // Yorumları kaldır (geliştirme yorumları)
  optimized = optimized.replace(/<!--[\s\S]*?-->/g, '');
  
  // Fazla satır sonlarını temizle
  optimized = optimized.replace(/\n\s*\n/g, '\n');
  
  return optimized.trim();
}

/**
 * Website'i dosya sistemine kaydet
 */
export async function saveWebsiteToFile(
  website: RenderedWebsite,
  outputPath: string
): Promise<void> {
  const fs = await import('fs/promises');
  const path = await import('path');
  
  // Dizini oluştur
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  
  // HTML'i kaydet
  await fs.writeFile(outputPath, website.html, 'utf-8');
  
  console.log(`Website saved to: ${outputPath}`);
}

/**
 * Website'i ZIP olarak oluştur
 */
export async function createWebsiteZip(
  website: RenderedWebsite,
  additionalFiles?: Record<string, string>
): Promise<Buffer> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  
  // Ana HTML dosyası
  zip.file('index.html', website.html);
  
  // Ayrı CSS dosyası (opsiyonel)
  if (website.css) {
    zip.file('styles.css', website.css);
  }
  
  // Ek dosyalar varsa (resimler, fontlar vb.)
  if (additionalFiles) {
    Object.entries(additionalFiles).forEach(([filename, content]) => {
      zip.file(filename, content);
    });
  }
  
  // README ekle
  const readme = `
# ${website.templateId} Website

Generated: ${new Date(website.generatedAt).toLocaleString()}
Locale: ${website.locale}

## How to use

1. Open index.html in your browser
2. Upload to your web hosting
3. Or deploy to GitHub Pages, Netlify, Vercel, etc.

---
Generated by NoCodePage AI
  `.trim();
  
  zip.file('README.md', readme);
  
  // ZIP'i oluştur
  return await zip.generateAsync({ type: 'nodebuffer' });
}

/**
 * Preview için güvenli HTML render et (sandbox)
 */
export function renderPreviewHtml(website: RenderedWebsite): string {
  // Güvenlik için bazı scriptleri devre dışı bırak
  let previewHtml = website.html;
  
  // External scriptleri kaldır (preview için)
  previewHtml = previewHtml.replace(/<script[^>]*src=[^>]*><\/script>/gi, '');
  
  // Inline scriptleri koru ama sandbox içinde çalıştır
  // (Bu preview için - production'da tüm scriptler çalışır)
  
  return previewHtml;
}
